<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <TargetFrameworks>net9.0-windows</TargetFrameworks>
    <ApplicationIcon>logo.ico</ApplicationIcon>
    <Product>H文件管理器</Product>
    <Description>电脑文件管理器：包括对文件的收藏、评分、打标签和按工程管理，支持多种预览方式（表格，缩率图，预览图等），对图片、视频支持预览，放大，缩小，对视频支持播放、截图、全屏播放、放大、缩小，定位到截图时间位置等，自定义收藏夹、标签夹</Description>
    <AssemblyVersion>1.0.0</AssemblyVersion>
    <FileVersion>1.0.0</FileVersion>
    <Copyright>Copyright © G 2024-2024</Copyright>
    <Authors></Authors>
    <PackageProjectUrl>https://github.com/G</PackageProjectUrl>    
    <Title>H文件管理器</Title>
    <Version>1.0.0</Version>
    <GeneratePackageOnBuild>Flase</GeneratePackageOnBuild>
    <Platforms>AnyCPU;x86</Platforms>
    <!--<SignAssembly>True</SignAssembly>-->
    <!--<AssemblyOriginatorKeyFile>H:\Github\WPF-Control\Key.snk</AssemblyOriginatorKeyFile>-->
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ApplicationBases\G.ApplicationBases.Default\G.ApplicationBases.Default.csproj" />
    <ProjectReference Include="..\..\ApplicationBases\G.ApplicationBases.Identify\G.ApplicationBases.Identify.csproj" />
    <ProjectReference Include="..\..\Controls\G.Controls.FavoriteBox\G.Controls.FavoriteBox.csproj" />
    <ProjectReference Include="..\..\Controls\G.Controls.FilterBox\G.Controls.FilterBox.csproj" />
    <ProjectReference Include="..\..\Controls\G.Controls.GridSplitterBox\G.Controls.GridSplitterBox.csproj" />
    <ProjectReference Include="..\..\Controls\G.Controls.OrderBox\G.Controls.OrderBox.csproj" />
    <ProjectReference Include="..\..\Controls\G.Controls.OutlookBar\G.Controls.OutlookBar.csproj" />
    <ProjectReference Include="..\..\Controls\G.Controls.PagerBox\G.Controls.PagerBox.csproj" />
    <ProjectReference Include="..\..\Controls\G.Controls.PropertyGrid\G.Controls.PropertyGrid.csproj" />
    <ProjectReference Include="..\..\Controls\G.Controls.RepositoryBox\G.Controls.RepositoryBox.csproj" />
    <ProjectReference Include="..\..\Controls\G.Controls.TagBox\G.Controls.TagBox.csproj" />
    <ProjectReference Include="..\..\Controls\G.Controls.Vlc\G.Controls.Vlc.csproj" />
    <ProjectReference Include="..\..\Controls\G.Controls.ZoomBox\G.Controls.ZoomBox.csproj" />
    <ProjectReference Include="..\..\Extensions\G.Extensions.ApplicationBase\G.Extensions.ApplicationBase.csproj" />
    <ProjectReference Include="..\..\Extensions\G.Extensions.BackgroundImage\G.Extensions.BackgroundImage.csproj" />
    <ProjectReference Include="..\..\Extensions\G.Extensions.FFMpeg\G.Extensions.FFMpeg.csproj" />
    <ProjectReference Include="..\..\Extensions\G.Extensions.Torrent\G.Extensions.Torrent.csproj" />
    <ProjectReference Include="..\..\Base\G.ValueConverter\G.ValueConverter.csproj" />
    <ProjectReference Include="..\..\Modules\G.Modules.Identity\G.Modules.Identity.csproj" />
    <ProjectReference Include="..\..\Modules\G.Modules.Login\G.Modules.Login.csproj" />
    <ProjectReference Include="..\..\Modules\G.Modules.Messages.Dialog\G.Modules.Messages.Dialog.csproj" />
    <ProjectReference Include="..\..\Modules\G.Modules.Messages.Form\G.Modules.Messages.Form.csproj" />
    <ProjectReference Include="..\..\Modules\G.Modules.Messages.Snack\G.Modules.Messages.Snack.csproj" />
    <ProjectReference Include="..\..\Modules\G.Modules.Operation\G.Modules.Operation.csproj" />
    <ProjectReference Include="..\..\Modules\G.Modules.Project\G.Modules.Project.csproj" />
    <ProjectReference Include="..\..\Modules\G.Modules.Theme\G.Modules.Theme.csproj" />
    <ProjectReference Include="..\..\Themes\G.Theme\G.Theme.csproj" />
    <ProjectReference Include="..\..\Windows\G.Windows.Dialog\G.Windows.Dialog.csproj" />
    <ProjectReference Include="..\..\Windows\G.Windows.Main\G.Windows.Main.csproj" />

    <ProjectReference Include="..\..\DataBases\G.DataBases.Sqlite\G.DataBases.Sqlite.csproj" />
    <ProjectReference Include="..\..\Modules\G.Modules.Messages.Dialog\G.Modules.Messages.Dialog.csproj" />
    <ProjectReference Include="..\..\Modules\G.Modules.Setting\G.Modules.Setting.csproj" />
    <ProjectReference Include="..\..\Modules\G.Modules.SplashScreen\G.Modules.SplashScreen.csproj" />
    <ProjectReference Include="..\..\Themes\G.Theme\G.Theme.csproj" />

    <ProjectReference Include="..\..\Presenters\G.Presenters.Repository\G.Presenters.Repository.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.16">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.16" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.77" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.21" />
  </ItemGroup>
  <!-- icon injected via Directory.Build.targets -->
</Project>

