<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Core.Controls</RootNamespace>
    <AssemblyName>Core.Controls</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core.Interfaces\Core.Interfaces.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="HalconDotNet">
      <HintPath>..\..\DLL\Halcon\halcondotnet.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
