<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\Controls\G.Controls.Form.PropertyItem\G.Controls.Form.PropertyItem.csproj" />
    <ProjectReference Include="..\..\Controls\G.Controls.Form\G.Controls.Form.csproj" />
    <ProjectReference Include="..\..\Controls\G.Controls.ProgressButton\G.Controls.ProgressButton.csproj" />
    <ProjectReference Include="..\..\Extensions\G.Extensions.FontIcon\G.Extensions.FontIcon.csproj" />
    <ProjectReference Include="..\..\Base\G.Attach\G.Attach.csproj" />
    <ProjectReference Include="..\..\Extensions\G.Extensions.Behvaiors\G.Extensions.Behvaiors.csproj" />
    <ProjectReference Include="..\..\Extensions\G.Extensions.Command\G.Extensions.Command.csproj" />
    <ProjectReference Include="..\..\Extensions\G.Extensions.Common\G.Extensions.Common.csproj" />
    <ProjectReference Include="..\..\Extensions\G.Extensions.Setting\G.Extensions.Setting.csproj" />
    <ProjectReference Include="..\..\Services\G.Services.Identity\G.Services.Identity.csproj" />
    <ProjectReference Include="..\..\Services\G.Services.Mail\G.Services.Mail.csproj" />
    <ProjectReference Include="..\..\Styles\G.Style\G.Style.csproj" />
    <ProjectReference Include="..\..\Themes\G.Theme\G.Theme.csproj" />
  </ItemGroup>
</Project>
