<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <ItemGroup>
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.77" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Extensions\G.Extensions.Common\G.Extensions.Common.csproj" />
    <ProjectReference Include="..\..\Extensions\G.Extensions.Geometry\G.Extensions.Geometry.csproj" />
    <ProjectReference Include="..\..\Extensions\G.Extensions.TypeConverter\G.Extensions.TypeConverter.csproj" />
    <ProjectReference Include="..\..\Base\G.ValueConverter\G.ValueConverter.csproj" />
    <ProjectReference Include="..\G.Controls.Adorner\G.Controls.Adorner.csproj" />
  </ItemGroup>
</Project>
