<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <LangVersion>latest</LangVersion>
    <DebugType>none</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.ValueTuple" />
    <Reference Include="ScottPlot">
      <HintPath>D:\C#\VM\WPF-Halcon-流程拖拉\02Plugins\014激光工具\00Exe\Plugins\ScottPlot.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="ScottPlot.WPF">
      <HintPath>D:\C#\VM\WPF-Halcon-流程拖拉\02Plugins\014激光工具\00Exe\Plugins\ScottPlot.WPF.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
