<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <ItemGroup>
    <ProjectReference Include="..\..\Extensions\G.Extensions.Behvaiors\G.Extensions.Behvaiors.csproj" />
    <ProjectReference Include="..\..\Extensions\G.Extensions.Mvvm\G.Extensions.Mvvm.csproj" />
    <ProjectReference Include="..\..\Services\G.Services.Message\G.Services.Message.csproj" />
    <ProjectReference Include="..\G.Controls.ZoomBox\G.Controls.ZoomBox.csproj" />
  </ItemGroup>
</Project>
