<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <ItemGroup>
    <ProjectReference Include="..\..\Base\G.ValueConverter\G.ValueConverter.csproj" />
    <ProjectReference Include="..\..\Styles\G.Style\G.Style.csproj" />
    <ProjectReference Include="..\..\Themes\G.Theme\G.Theme.csproj" />
    <ProjectReference Include="..\G.Windows.Main\G.Windows.Main.csproj" />
  </ItemGroup>
</Project>
