<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="QRCoder.Xaml" Version="1.4.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Extensions\G.Extensions.Common\G.Extensions.Common.csproj" />
    <ProjectReference Include="..\..\Styles\G.Style\G.Style.csproj" />
  </ItemGroup>
</Project>
