<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <GeneratePackageOnBuild>Flase</GeneratePackageOnBuild>
    <UseWPF>true</UseWPF>
    <Product>H大师</Product>
    <Description>电脑参数：可以查看处理器、内存、硬盘、网卡、显卡、操作系统、安装软件等</Description>
    <AssemblyVersion>1.0.2</AssemblyVersion>
    <FileVersion>1.0.0</FileVersion>
    <Copyright>Copyright © G 2019-2023</Copyright>
    <Authors></Authors>
    <PackageProjectUrl>https://github.com/G</PackageProjectUrl>
    <Title></Title>
    <Version>1.0.3</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Extensions\G.Extensions.ApplicationBase\G.Extensions.ApplicationBase.csproj" />
    <ProjectReference Include="..\..\Extensions\G.Extensions.AppPath\G.Extensions.AppPath.csproj" />
    <ProjectReference Include="..\..\Modules\G.Modules.Messages.Dialog\G.Modules.Messages.Dialog.csproj" />
    <ProjectReference Include="..\..\Modules\G.Modules.Setting\G.Modules.Setting.csproj" />
    <ProjectReference Include="..\..\Modules\G.Modules.SplashScreen\G.Modules.SplashScreen.csproj" />
    <ProjectReference Include="..\..\Themes\G.Theme\G.Theme.csproj" />
    <ProjectReference Include="..\..\Windows\G.Windows.Dialog\G.Windows.Dialog.csproj" />
  </ItemGroup>

</Project>

