<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0-windows</TargetFrameworks>
    <UseWPF>true</UseWPF>
    <RootNamespace>Plugin.ImageAcquisition</RootNamespace>
    <AssemblyName>Plugin.ImageAcquisition</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Services\Core.Halcon\Core.Halcon.csproj" />
    <ProjectReference Include="..\..\Shard\Core.Controls\Core.Controls.csproj" />
    <ProjectReference Include="..\..\Shard\Core.Interfaces\Core.Interfaces.csproj" />
    <ProjectReference Include="..\..\UI\Controls\UI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Prism.Wpf" Version="9.0.537" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="halcondotnet">
      <HintPath>..\..\DLL\Halcon\halcondotnet.dll</HintPath>
    </Reference>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="copy $(TargetPath) $(SolutionDir)\Modules\$(TargetFileName) /Y" />
  </Target>
</Project>
