<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <ItemGroup>
    <PackageReference Include="log4net" Version="2.0.15" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Services\G.Services.Common\G.Services.Common.csproj" />
    <ProjectReference Include="..\G.Extensions.Setting\G.Extensions.Setting.csproj" />
  </ItemGroup>
</Project>
