<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\Controls\G.Controls.Adorner\G.Controls.Adorner.csproj" />
    <ProjectReference Include="..\..\Extensions\G.Extensions.Behvaiors\G.Extensions.Behvaiors.csproj" />
    <ProjectReference Include="..\..\Extensions\G.Extensions.Common\G.Extensions.Common.csproj" />
    <ProjectReference Include="..\..\Extensions\G.Extensions.Geometry\G.Extensions.Geometry.csproj" />
    <ProjectReference Include="..\..\Extensions\G.Extensions.TypeConverter\G.Extensions.TypeConverter.csproj" />
    <ProjectReference Include="..\..\Base\G.ValueConverter\G.ValueConverter.csproj" />
    <ProjectReference Include="..\..\Services\G.Services.Common\G.Services.Common.csproj" />
    <ProjectReference Include="..\..\Services\G.Services.Identity\G.Services.Identity.csproj" />
    <ProjectReference Include="..\..\Styles\G.Style\G.Style.csproj" />
  </ItemGroup>
</Project>
