<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>logo.ico</ApplicationIcon>
    <GeneratePackageOnBuild>Flase</GeneratePackageOnBuild>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.77" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\Controls\G.Controls.Chart2D\G.Controls.Chart2D.csproj" />
    <ProjectReference Include="..\..\Controls\G.Controls.RepositoryBox\G.Controls.RepositoryBox.csproj" />
    <ProjectReference Include="..\..\DataBases\G.DataBases.Sqlite\G.DataBases.Sqlite.csproj" />
    <ProjectReference Include="..\..\Datas\G.Data.Test\G.Data.Test.csproj" />
    <ProjectReference Include="..\..\Extensions\G.Extensions.ApplicationBase\G.Extensions.ApplicationBase.csproj" />
    <ProjectReference Include="..\..\Extensions\G.Extensions.AppPath\G.Extensions.AppPath.csproj" />
    <ProjectReference Include="..\..\Extensions\G.Extensions.BackgroundImage\G.Extensions.BackgroundImage.csproj" />
    <ProjectReference Include="..\..\Modules\G.Modules.Identity\G.Modules.Identity.csproj" />
    <ProjectReference Include="..\..\Modules\G.Modules.Login\G.Modules.Login.csproj" />
    <ProjectReference Include="..\..\Modules\G.Modules.Messages.Dialog\G.Modules.Messages.Dialog.csproj" />
    <ProjectReference Include="..\..\Modules\G.Modules.Messages.Form\G.Modules.Messages.Form.csproj" />
    <ProjectReference Include="..\..\Modules\G.Modules.Operation\G.Modules.Operation.csproj" />
    <ProjectReference Include="..\..\Modules\G.Modules.Setting\G.Modules.Setting.csproj" />
    <ProjectReference Include="..\..\Modules\G.Modules.SplashScreen\G.Modules.SplashScreen.csproj" />
    <ProjectReference Include="..\..\Modules\G.Modules.Theme\G.Modules.Theme.csproj" />
    <ProjectReference Include="..\..\Themes\G.Theme\G.Theme.csproj" />
    <ProjectReference Include="..\..\Windows\G.Windows.Dialog\G.Windows.Dialog.csproj" />
    <ProjectReference Include="..\..\Windows\G.Windows.Main\G.Windows.Main.csproj" />
  </ItemGroup>
  <!-- icon injected via Directory.Build.targets -->
</Project>
